### ISSUE TITLE
Correction in CP_SOLVER file

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#10]
Dear Eralp,

I wanted to bring to your attention a small correction that I believe needs to be made in the subroutine. The correction pertains to lines 1857 and 2915.
In the latest code line no are 1848 and 2906

In both of these lines, the current formula reads as follows:
dstranp33 = 0.5*(Lp - transpose(Lp))*dt

After carefully reviewing the code, I believe that the negative sign in these lines should be replaced with a positive sign, resulting in the corrected formula:
dstranp33 = 0.5*(Lp + transpose(Lp))*dt

I kindly request you to review this correction and provide your comments or suggestions. Your timely response would be greatly appreciated.

Thank you for your attention to this matter.

Best regards,
Vikram Roy

**Comment by EralpDemir** [comment]
Thanks Vikram, good catch.

Eralp
