### ISSUE TITLE
Cancellation of positive and negative slip

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#11]
Hi Eralp,

I have a question regarding the coding of the "gammasum" variable in the latest version of the code.

In the previous versions of the code, it was implemented as follows:
! Total slip over time per slip system
gammasum = 0.
do is = 1, nslip
    gammasum(is) = gammasum_t(is) + abs(gammadot(is)) * dt
enddo
However, in the current version of the code, it is written as:

! Total slip over time per slip system
gammasum = 0.
do is = 1, nslip
    gammasum(is) = gammasum_t(is) + gammadot(is) * dt
enddo
I have concerns about the logic behind the current implementation. Since slip is an irreversible process, it seems unlikely that positive and negative slip would cancel each other out perfectly at the same location. Could you please clarify these queries and provide an explanation for the change in the code?

Thank you for your assistance.

**Comment by EralpDemir** [comment]
Hi,
We use total slip without the sign in the current implementation. Slip has a sign and it can reverse direction.

There are hardening models based on the cumulative slip and in those occurances total slip might be used as the absolute sum, but we do not use such laws in the code.

It might be used for a different purpose in the former version, we do absolute value for  strain hardening, but it is not based on the total sum but the absolute increment of slip.

Bests,
Eralp

**Comment by EralpDemir** [comment]
Thanks Vikram, I realized sum of slip was used in the creep law, so you are correct. We wanted to the locations of positive and negative slip, but thinking that this sum of slip per slip system were not used in any of the constitutive laws. But indeed it is used in creep law, so it needs to be corrected.

I will publish v1.35 considering that update.

Many thanks,
Eralp
