### ISSUE TITLE
all stresses are zero

### ISSUE THREAD

**Issue by mikejwg** [TarletonGroup/CrystalPlasticity#12]
Dear authors,

We try to a tensile test including  only one element and one grain  based on  UMAT v1.33.  We output STRESS and Sigma in the Umat.f.  The displacement is correct, but all values are zero during tension.  The material properties were used as the same as the testcase.inp.
Any comments are very appreciated.

**Comment by EralpDemir** [comment]
Sorry for my late response.

I have updated the example/testcase.inp file and added uni-axial boundary conditions. It is working now.

Please let me if there are any further issues.

Thanks,
Eralp
