### ISSUE TITLE
Correction in CRSS File

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#13]
Dear Erlap,

I would like to bring to your attention a correction that needs to be made in the CRSS file. In the file, the variable "sintmat2" is declared with a dimension of nslip x nslip. However, I believe the size of this variable should be nslip x maxnloop, based on its later usage in a nested loop. The outer loop iterates from 1 to nslip, while the inner loop iterates from 1 to maxnloop. 

Or Dimension of 1,  maxnloop will also be sufficient provided the interation coefficient is same for all slip systems

Here is the relevant code snippet:

!         Number of defects        
nloop = int(irradiationparam(1))
do is = 1, nslip
    do il = 1, 3
        Ploop(is) = Ploop(is) +
        + sintmat2(is,il)**2. * loop(il)
    end do
end do

Could you please review this and provide a suitable correction or clarification?

Thank you.

Best regards,
Vikram

**Comment by EralpDemir** [comment]
Thank you Vikram for your careful review.

That is something we have done intentionally. We have defined two hardening and strength interaction matrices for each material. We used the 2nd strength and hardening (softening) interaction matrices for the irradiation. In that  case only a fraction of these matrices is used. It is just to avoid another definition of two more matrices for each material.

Please make sure to use the latest version (v1.36), I have found and fixed a few corrections about the calculation of outputs (lattice strains) and a major fix about the calculation of Lp. 

I have added an explanation for the derivation for the orientation update for the Forward gradient and Dunne methods regarding your earlier comment about orientation updates. Please have a look at those in the documentation and let me know if you have question. 

Best wishes,
Eralp
