### ISSUE TITLE
Correction in File Initializations.f

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#17]
Dear Eralp,

In the file globalvariables.f, lines 260-268 define the variables statev_ssd and statev_ssdtot as follows:

```fortran
! SSD density per slip system at current time step
real(8), allocatable, public :: statev_ssd(:,:,:)

! SSD density per slip system at former time step
real(8), allocatable, public :: statev_ssd_t(:,:,:)

! Total SSD density at current time step
real(8), allocatable, public :: statev_ssdtot(:,:)

! Total SSD density at former time step
real(8), allocatable, public :: statev_ssdtot_t(:,:)
```

This leads me to believe that `statev_ssdtot` represents the total ssd density at the current time step. However, I found a discrepancy in the file `Initializations.f`, lines 573-579, where these variables are initialized:

```fortran
! Initialize ssd density per slip system
statev_ssd(noel,npt,1:maxnslip) = rho_0
statev_ssd_t(noel,npt,1:maxnslip) = rho_0

! Initialize total ssd density
statev_ssdtot(noel,npt) = rho_0(1)
statev_ssdtot_t(noel,npt) = rho_0(1)
```

The variable `rho_0` is read from `props` and represents the initial dislocation density for each slip system. It appears that the initialization for `statev_ssdtot` and `statev_ssdtot_t` is using only the dislocation density of the first slip system, which might not be correct.

I suggest a correction to the initialization of `statev_ssdtot` and `statev_ssdtot_t` to ensure it represents the total SSD density:

```fortran
! Initialize ssd density per slip system
statev_ssd(noel, npt, 1:maxnslip) = rho_0
statev_ssd_t(noel, npt, 1:maxnslip) = rho_0

! Initialize total ssd density
statev_ssdtot(noel, npt) = sum(rho_0) ! Sum of dislocation density over all slip systems, representing total SSD density
statev_ssdtot_t(noel, npt) = sum(rho_0) ! Sum of dislocation density over all slip systems at former time step
```

By making this correction, `statev_ssdtot` will now be properly initialized as the sum of dislocation density over all slip systems, which represents the total SSD density.

Kindly review this suggestion and provide any necessary clarifications or corrections.

Thank you.

Sincerely,
Vikram Roy

**Comment by EralpDemir** [comment]
Thanks Vikram,

The variable name is total density but it is used in one of the strain hardening laws to account for isotropic hardening. The name of the variable maybe is misleading, it should be single density or average density.

The initial value is the same as initial density because it should remain the same to not to change the strength (tauc) from the expected value. Therefore I would keep it as the initial density.

Many thanks for your comment, with that I close this issue. Please let me know if you'd have any further questions.

Best wishes,
Eralp
