### ISSUE TITLE
Difference Between sintmat1 (Strength Interaction Matrix for Dislocations) & hintmat1 (hardening Interaction Matrix for Dislocations)

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#18]
Dear Eralp,

Thank you for providing clarification on the variable `statev_ssdtot` in the file `Initializations.f`. I have another question now, which relates to the `sintmat1` and `hintmat1` matrices used for dislocations.

I understand that the strength interaction matrix elements, represented by `aij`, are utilized to calculate the CRSS (Critical Resolved Shear Stress) due to forest hardening, as shown in the following formula:

```
tau_crss(i) = G12 * burgerv * sqrt(aij * rhoj)
```

where `tau_crss(i)` denotes the CRSS of slip system `i`, `G12` is a material constant, `burgerv` is the magnitude of the Burgers vector, and `rhoj` corresponds to the dislocation density on the slip system.
<img width="516" alt="6" src="https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/30971c63-7302-442c-ab55-4e9733ccc743">

While this formula and the values used by Monnet et. al. 2019 for austenitic stainless steel are clear, I am currently facing confusion regarding the `hintmat1` matrix. Unfortunately, I couldn't find any details about its use, meaning, or application in the documentation or source code.

Could you please provide insight into the purpose of the `hintmat1` matrix and any references where these hardening interaction matrices are employed?

Thank you for your assistance.

Best regards,
Vikram Roy

**Comment by EralpDemir** [comment]
Many thanks Vikram. You are asking good questions.

Actually, there are variety of different ways interaction matrices are utilized in the literature. A recent paper has a nice overview about these approaches: http://dx.doi.org/10.1016/j.ijplas.2012.10.010

Some use the same coefficients for strength and hardening interactions (Kubin). Some different. But latent hardening is an accepted phenomenon in crystal mechanics. This states that slip going on one slip system causes strain hardening on another system more than the system it belongs to. Therefore, latent hardening matrices were used to account for that.

The hintmat variable is actually used for this purpose. The hardening model -1 is actually commonly used Voce type hardening together with latent hardening. I am sending some links for further reading for latent hardening.

Earlier studies:

Wu, T.Y., Bassani, J.L. and Laird, C., 1991. Latent hardening in single crystals-I. Theory and experiments. Proceedings of the Royal Society of London. Series A: Mathematical and Physical Sciences, 435(1893), pp.1-19.

https://doi.org/10.1016/0001-6160(85)90154-3

An application in CPFEM modeling:
https://doi.org/10.1016/0022-5096(92)80003-9

A recent paper for a crack modelign application:
https://doi.org/10.1016/j.ijplas.2018.11.012

Best wishes,
Eralp
