### ISSUE TITLE
How to call the external functions involved in the subroutines？

### ISSUE THREAD

**Issue by mubellyb** [TarletonGroup/CrystalPlasticity#2]
When I tried to use the UMAT subroutine(Abaqus2020 + Visual studio 2019 + Intel Fortran 2020 on the Windows), the function subroutine "lapverse" in the file "utils.f" called the external functions "DGETRF" and "DGETRI". And they also called more external functions, perplexingly. 

I looked for these external functions and it seems that come from the function library "LAPACK", but I don't know how to call the functions in "LAPACK" when running the UMAT subroutine.

Looking forward to your reply, thanks.

**Comment by TarletonGroup** [comment]
You need to add the /mkl flag to your abaqus environment file.

We will soon publish a new version of the code which doesn’t use the  intel math kernel library.

Best wishes

Ed

Sent from my iPhone

On 25 Feb 2023, at 12:08, mubellyb ***@***.***> wrote:

﻿

When I tried to use the UMAT subroutine(Abaqus2020 + Visual studio 2019 + Intel Fortran 2020 on the Windows), the function subroutine "lapverse" in the file "utils.f" called the external functions "DGETRF" and "DGETRI". And they also called more external functions, perplexingly.

I looked for these external functions and it seems that come from the function library "LAPACK", but I don't know how to call the functions in "LAPACK" when running the UMAT subroutine.

Looking forward to your reply, thanks.
