### ISSUE TITLE
Boundary Condition of Testcase.inp-ABAQUS error

### ISSUE THREAD

**Issue by zz123-fix** [TarletonGroup/CrystalPlasticity#21]
Dear Eralp
Thank you very much for sharing this CrystalPlasticity code, it helps me a lot.
The testcase.inp dosen't have boundary condition, so I add boundary condition according to your video tutorials, but I got an error:

**Too many attempts made for this increment.**
 Abaqus/Standard 2021                  DATE 14-8-2023 TIME 11:47:12
 SUMMARY OF JOB INFORMATION:
 STEP  INC ATT SEVERE EQUIL TOTAL  TOTAL      STEP       INC OF       DOF    IF
               DISCON ITERS ITERS  TIME/    TIME/LPF    TIME/LPF    MONITOR RIKS
               ITERS               FREQ
   1     1   1U    0     1     1  0.00       0.00       0.01000   
   1     1   2U    0     1     1  0.00       0.00       0.005000  
   1     1   3U    0     1     1  0.00       0.00       0.002500  
   1     1   4U    0     1     1  0.00       0.00       0.001250  
   1     1   5U    0     1     1  0.00       0.00       0.0006250 
                          
 THE ANALYSIS HAS NOT BEEN COMPLETED

Would you happen to know where the problem should be? All the comments and suggestions are a tremendous help to me.

Sincerely,
zz123

![1](https://github.com/TarletonGroup/CrystalPlasticity/assets/85141086/3385f07e-7abe-4f07-b334-212537185f54)
![2](https://github.com/TarletonGroup/CrystalPlasticity/assets/85141086/60965bcc-2d0c-4102-9da4-1208886b973b)

**Comment by vikramroybarc** [comment]
Hi,
I will recommend  you to try the cpfem for a simple case like one element  problem with time increment  in range of 1e-5 to 1e-3, length in units of um and Stress MPa 
And then move to complex case.

**Comment by happymiaomiao0323** [comment]
Hello, I am a little confused. In ABAQUS, shouldn't the length unit mm and the stress unit MPa correspond to each other?

**Comment by zz123-fix** [comment]
> 

I will have a try. Thank you.

**Comment by EralpDemir** [comment]
Hi, your BCs seem a little stiff to me. Make sure to define them on the surface nodes only, not the elements.

If the BCs are stiff, then you may have end up with large stresses. I like the suggestion to use smaller time increments. 

If you are using force BCs, try to adjust the magnitude considering the dimensions as micrometer and stress unit as MPa.

Bests,
Eralp

**Comment by vikramroybarc** [comment]
> Hello, I am a little confused. In ABAQUS, shouldn't the length unit mm and the stress unit MPa correspond to each other?

It depends upon the mass unit you choose- g or Kg
