### ISSUE TITLE
There are questions about Hcp and creep.

### ISSUE THREAD

**Issue by happymiaomiao0323** [TarletonGroup/CrystalPlasticity#22]
Dear Eralp
Thank you very much for sharing this CrystalPlasticity code, it helps me a lot.
Q1：
When I use the HCP model you provided, that is, case(3) in usermaterials.f, the program will terminate and the following error message will appear.
  INCREMENT     1 STARTS. ATTEMPT NUMBER  1, TIME INCREMENT  1.000E-02
 ***ERROR: Analysis is being terminated from a user subroutine

Q2：When I use case(2) like the tutorial you provided, everything works as usual, 
but when I use the creep model provided in the program, the program will report an error as follows:
     CONTACT FORCE ERROR TOLERANCE FOR CONVERT SDI=YES                 1.00

Among them, the creep parameters I used are as follows:
!     Obtain creep parameters
!     reference creep rate (1/s)
          creepparam(1) = 10.d-8
!     creep stress multiplier (1/MPa)
          creepparam(2) = 0.
!     activation energy for creep (J/mol)
          creepparam(3) = 650.d3
!     reference damage rate (1/s)
          creepparam(4) = 0.
!     damage stress multiplier (1/MPa)
          creepparam(5) = 0.
!     activation energy for damage (J/mol)
          creepparam(6) = 0.
Would you happen to know where the problem should be? All the comments and suggestions are a tremendous help to me.

Sincerely,
Xusheng

**Comment by EralpDemir** [comment]
Hi Xucheng,

Q1.
Make sure to set the parameter "maxnslip" in userinputs.f to 30 when using hcp.

Q2. 
I have not used the creep law much. Your parameter settings seem correct. It may not like zeros, please check the creep rate the law and its derivative in "creep.f" for any 1/0 errors. 

I will double check this once I am back in the office.

Bests,
Eralp

**Comment by happymiaomiao0323** [comment]
Thank you very much for your answer and look forward to your guidance again.

**Comment by EralpDemir** [comment]
I keep your last issue as open so close this one. 

Please try the latest version 2.4 and let me know.

Bests,
Eralp

**Comment by nyf-yellow** [comment]
Hi Xucheng,
  I also test the creep.f in version 2.4. I apply a constant pressure on my model, but I find that creep don't contribute to the deformation. Can you tell me how you set the boundary conditions 

Bests,
Yvfei Nie

**Comment by EralpDemir** [comment]
Hi, could you please use v2.5 because I remember a correction related with creep. 

I leave this issue open until resolved.

Thanks,
Eralp
