### ISSUE TITLE
Grain size effect 

### ISSUE THREAD

**Issue by mikejwg** [TarletonGroup/CrystalPlasticity#24]
Dear code developer,
We tired a serial of simulations to study the grain size effect (for exampel HP rule).  Two cases were simulated firstly.  The RVE includes 200 grains and the average grain size is about 30 micrometer or 300 micrometer (These two cases have exactly the same Euler Angle distributions).   FCC copper is used (MatID=5 in the code) for verification. In my input and usermaterials.f, Units of stress is MPa. Dimension units are micrometers  The RVE generators also generate models with micrometer dimensions.
According to HP rule, the strength of 30 micron grains  should be much higher than that of 300 micron grains. But in our simulations, the calculated results do show that the macroscopic stress-strain curves of the two cases basically coincide. 
Did we neglect to modify any parameters? Any suggestions are very appreciated.

Best regards,
Mike Jiang

**Comment by EralpDemir** [comment]
Hi Mike,

Have you turned the gndmodel flag on? It is in userinputs.f. GNDs are necessary for size dependence. Please try and let me know.

Thanks,
Eralp

**Comment by mikejwg** [comment]
Dear Eralp，

Thanks for your suggestion. Now the code works well when gndmodel was turned on. 

Best regards,
Mike Jiang
