### ISSUE TITLE
Is it possible to support element C3D8R?

### ISSUE THREAD

**Issue by 123fgh123** [TarletonGroup/CrystalPlasticity#25]
Dear Eralp:

Thanks a lot for sharing this code, and it deepens my understanding to crystal plasticity.

I want to know, is it possible to add element C3D8R in this code?

When I run this code with element C3D8 (element number is 128X128X128=2097152), it requires a very large RAM (about 300GB) to operate, it is also a time-consuming work (46h with 48 cpus, Intel(R) Xeon(R) CPU E5-4640 v3 @ 1.90GHz) and the .odb file is quite large (about 33GB).  Attached are my simulation files.

It would be great if the element C3D8R could be supported in this CrystalPlasticity code.

[sim_file.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/12397408/sim_file.zip)

Kind regards,

Guofeng

**Comment by EralpDemir** [comment]
Hi Guofeng,

I have added the C3D8R element type to the library. You should use some small number for hourglass stiffness and GND model does not work for this type of element. 

I have checked this element type, please let me know if you encounter any issues.

Bests,
Eralp

**Comment by 123fgh123** [comment]
Hi Eralp，

Thank you very much for your reply. I will try.

Yours sincerely,

Guofeng

**Comment by 123fgh123** [comment]
Hello Eralp:

I have found some problems when I run the code. I attached simulation files in the following link.

https://zenodo.org/record/8285425

Yours sincerely,

Guofeng

**Comment by EralpDemir** [comment]
I have fixed this bug. Many thanks for the heads, it is related with calculation of gradients for elements with a single integration point. 

Please try version 2.4 and let me know how it works.
Bests,
Eralp

**Comment by 123fgh123** [comment]
Hello Eralp:

Thanks for your reply.

I have tried V2.4, it seems does not work. see attached files.
[Test-20230828.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/12454143/Test-20230828.zip)

Yours sincerely,

Guofeng

**Comment by EralpDemir** [comment]
Dear Guofeng,

You have use the material-ID consistent with your phase. In your model you use materialID=2 which is for FCC but the maxnslip is set 30 which is for HCP. I changes maxnslip to 12 which gave consistent results. Please see the screenshot.
![Untitled](https://github.com/TarletonGroup/CrystalPlasticity/assets/90987045/46c5cfd9-5540-445a-9474-9de11dda3689)



The reduced integration elements need an appropriate hourglass stiffness to run. You have to pick a proper value for that.

Hope this helps,
Eralp

**Comment by 123fgh123** [comment]
Hello Eralp:

It works.  

Thank you very much.

Yours sincerely,

Guofeng

**Comment by 123fgh123** [comment]
Dear Eralp:

I have found another issue in V2.4.

When element C3D8 is employed and its number is large (128X128X128), it cannot work. But if the number is reduced to 128X64X64, it works well. For element C3D8R, it works well in 128X128X128 and 128X64X64. Please see attached link.
https://zenodo.org/record/8294076

Actually, this issue also exists in the previous version of the CP code, such as V2.2 and V2.3. This issue seems to be related to the version of Abaqus and IntelFortran, when Abaqus6.14+IntelFortran2013 is employed , it works well. For Abaqus2021+IntelFortran2021 and Abaqus2022+IntelFortran2021, it cannot work. Please see another link.
https://zenodo.org/record/8285425

My hardware : CPU: 2 x Intel Xeon ICX Platinum 8358 (2.6GHz, 32 cores),  Mem: 16 x 32GB TruDDR4 3200 MHz (2Rx8 1.2V) RDIMM, and OS is CentOS Linux release 8.3.2011.

Yours sincerely,
Guofeng

**Comment by EralpDemir** [comment]
Dear Guofeng,

There is no maximum limit on the element number. Just make sure to set the element number in userinputs.f. If so, it could be a memory problem.

Your system seems to have enough memory. Make sure to utilize all the memory. You may find an example runner file for the HPC in Oxford (ARC) which is also a linux system.

Bests,
Eralp

**Comment by 123fgh123** [comment]
Dear Eralp:

Actually, I have checked userinputs.f many times and the set of element number is right.

As for my systerm，the available memory is 64X8=512 GB，and I have checked that 128X128X128 C3D8 elements will consume about 300GB memory when runring, which means the memory available is enough.  

I have found that my systerm is quite same as that of Oxford (ARC) , such as Intel Xeon Platinum CPU and CentOS 8.

What confuses me is that 128X128X128 C3D8R elements works well, but C3D8 not.  And Abaqus6.14+IntelFortran2013 works well (in another systerm, Intel Xeon Platinum CPU and CentOS 7, the available memory is 48X8=384GB ).

**Comment by 123fgh123** [comment]
Dear Eralp:

Actually, I have checked userinputs.f many times and the set of element number is right.

As for my systerm，the available memory is 64X8=512 GB，and I have checked that 128X128X128 C3D8 elements will consume about 300GB memory when running, which means the memory is enough.  

I have found that my HPC systerm is quite similar to that of Oxford (ARC) , such as Intel Xeon Platinum CPU and CentOS 8.

What confuses me is that 128X128X128 C3D8R elements works well, but C3D8 not.  And for Abaqus6.14+IntelFortran2013,  it also works well (in another systerm, Intel Xeon Platinum CPU and CentOS 7, the available memory is 48X8=384GB).

Some people said that new version of UMAT use JSTEP (array), rather than KSTEP (scalar) in its previous version, see following link. I have tried to modified this issue, but it seems does not work.  
https://community.intel.com/t5/Intel-Fortran-Compiler/seg-fault-for-Abaqus-2020/td-p/1418080

new version of UMAT (such as abaqus 6.14) :
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/64315155/289cf1b1-785f-476c-8f89-1d104a22c9d9)

old version of UMAT (such as abaqus 6.11):
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/64315155/6b557b0a-dbcb-4934-8d7d-aa388afcd9d3)

your UMAT:
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/64315155/df75070b-77ea-41d5-893c-d67d41386d10)


Bests,
Guofeng

**Comment by EralpDemir** [comment]
Thanks Guofeng for pointing out this, KSTEP is not used elsewhere so I do not think it is the issue.

So when you have used less number of elements (1000) with C3D8 you did not have any issue but when you increased the element number to 10^6, you started having problems. This  seems like a memory issue. Make sure to allocate the maximum memory when running the job. 

I have tested  the code in ARC for a large scale problem and I did not have an issue. I will redo that test with all the modifications and share the results with you. But please do not expect a quick answer soon due to my other responsibilities.

Bests,
Eralp

**Comment by EralpDemir** [comment]
Dear Guofeng,
I realized an issue when inverting by singular value decomposition (I simply set "SVDinversion=0" in userinputs.f). That might also be causing the problem.

Could you please check how the version in the Github works your case and let me know?

Thanks,
Eralp

**Comment by 123fgh123** [comment]
Dear Eralp,

I will have a try according to your suggestion.

Several days ago, I reduced the element number from 128X128X128 to 128X128X110 (about 15% reduction), the RAM consumed reduced from 300GB to about 260GB, and I found it works well.

Bests,
Guofeng

**Comment by EralpDemir** [comment]
Thank you so much for your feedback.

We are looking for means to reduce the memory requirement now. I will keep you posted with progress.

Best wishes,
Eralp

**Comment by 123fgh123** [comment]
Dear Eralp,

The code works well if SVDinversion was set to 0. Some simulation files are attached in the following link, and hope it to be helpful for your future work. (The simulation was terminated manually to save computing resources)
https://doi.org/10.5281/zenodo.8320420

Bests,
Guofeng

**Comment by EralpDemir** [comment]
Many thanks Goufeng.
