### ISSUE TITLE
Creep

### ISSUE THREAD

**Issue by happymiaomiao0323** [TarletonGroup/CrystalPlasticity#26]
Dear Eralp
Thank you very much for sharing this CrystalPlasticity code, it helps me a lot.
In creep.f, the second parameter you provided is expressed as bc = creepparam(5).
 Have you ever used creep when using the code?
!     Obtain creep parameters
!     reference creep rate (1/s)
      gammadotc = creepparam(1)
!     creep stress multiplier (1/MPa)
      bc = creepparam(5)
!     activation energy for creep (J/mol)
      Qc = creepparam(3)
!     reference damage rate (1/s)
      gammadotd = creepparam(4)
!     damage stress multiplier (1/MPa)
      bd = creepparam(5)
!     activation energy for damage (J/mol)
      Qd = creepparam(6)
!

**Comment by EralpDemir** [comment]
Hi,
I checked the creep model with the model parameters of materialID-5 in usermaterials.f.  It works, I have made a small correction in the creep.f to reset Dp.

Please try version 2.4 and let me know how it works.

Bests,
Eralp

**Comment by happymiaomiao0323** [comment]
Hi,
I will do it,thank you.

**Comment by EralpDemir** [comment]
Hi,
I have used an HCP model (the material ID=3) with the same creep coefficients in model 5. I am sending the usermaterial.f file as a txt file.
[usermaterials.txt](https://github.com/TarletonGroup/CrystalPlasticity/files/12450863/usermaterials.txt)

There are two points that requires attention when creep modeling:

1. The exponential law is quite sensitive model parameters. Please make sure to check the coefficients to result in reasonable numbers. Usually slip rate is in the order 10^-8 1/s for creep.


2. The creep laws usually should be used with slip laws for getting plasticity especially when you are using displacement controlled boundary conditions. The elastic response without plasticity lead to high levels of stresses finally leading to convergence issues.
