### ISSUE TITLE
Questions about stress curves

### ISSUE THREAD

**Issue by happymiaomiao0323** [TarletonGroup/CrystalPlasticity#27]
Dear Eralp
When I use case(3) in usermaterials.f, the stress curve I extracted is as shown in the figure below. In my opinion, the normal stress curve should not have this period of decline.The boundary conditions are imposed consistent with the case you provided. I would like to know which parameter affects this stress result.

![job-2-STRESS](https://github.com/TarletonGroup/CrystalPlasticity/assets/106541634/f872c7a4-bc6c-4d48-91dc-3cdfbffc10f2)

**Comment by EralpDemir** [comment]
Hi,
Material model-3 has an irradiation hardening by default. This is related with irradiated material behavior in which the material experiences strain softening after yield which saturates after certain strain. This behaviour is included to the model you have selected. Please turn off irradiation hardening by setting the parameter "irradiationmodel" to "0".
Thanks,
Eralp
