### ISSUE TITLE
Issue of material property?

### ISSUE THREAD

**Issue by 123fgh123** [TarletonGroup/CrystalPlasticity#28]
Dear Eralp,

Recently，I generated a RVE with 3 grains and set different material property（hardeningparam1）to them，see following figure and “!!!Sum.xlsx” in attached link.

 
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/64315155/0b4ac307-ce83-406a-b5f3-2e698cd9ea08)

I found that the Mises stress extracted from Grain 3 (element 910) in Job8-1 and Job10-1 have the same value (see following figure and “!!!Sum.xlsx” in attached link), despite the difference of material property.

 
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/64315155/945dcce7-0dc3-428f-8d20-7690b187679d)

I don’t know whether it is the issue of the code. The sim files are attached in the following link.

https://doi.org/10.5281/zenodo.8385099

Bests,
Guofeng

**Comment by EralpDemir** [comment]
Dear Guofeng,
You have used the PROPS, it might be linked with the ordering of the inputs. 

Could you please try entering the material properties using usermaterials.f (hardening parameters start at line 522) and let me know?

Thanks,
Eralp

**Comment by EralpDemir** [comment]
Hi Guofeng,
There are 48 entries in the PROPS for rho0, tauc0, and burgers vector. It seems it has 30 as in the earlier version. Please correct this and let me know.

Bests,
Eralp

**Comment by 123fgh123** [comment]
Dear Eralp,

I used V2.4 to conduct the simulation, where there are 48 entries in the PROPS for rho0, tauc0, and burgers vector. 

What confuses me is that Job9-1 seems to work well, but Job10-1 was not.

I will try usermaterials.f as you suggested.

Bests,
Guofeng

**Comment by EralpDemir** [comment]
Hi Guofeng,

I checked your .inp file I counted 30 entries for rho0. It may still work if some of tauc values are nonzero but you get definitely wrong results. Please check your PROPS entry. Let me know if I am mistaken.

Thanks

**Comment by 123fgh123** [comment]
I copied PROPS entries from my .inp files and listed them in the attached table, I counted them but did not know how to get the number of 30.

[Job-PROPS-sum.xlsx](https://github.com/TarletonGroup/CrystalPlasticity/files/12747488/Job-PROPS-sum.xlsx)

**Comment by EralpDemir** [comment]
Ok, thanks for clarifying that. I might have counted wrong, sorry for that. 

I can see the problem here though. Currently we cannot assign different properties to grains. We can assign different phases though. Each phase in the mesh shall have one material property. 

Please check this by changing the properties uniformly for all the grains.

Hope this helps,
Eralp

**Comment by 123fgh123** [comment]
Dear Eralp,

I have used usermaterials.f to define the material property, and the result seems to be reasonable. See following link.

https://doi.org/10.5281/zenodo.8388310

I copied material 2 (case (2)) in usermaterials.f  to material 11 (case (2)) , and only the hardeningparam1 was modified to 100. in  material 11 (see line 567~765 in modified usermaterials.f).  With this method, I could define grains with different hardeningparam1.

I found that the hintmat1 was defined in a different way between usermaterials.f and PROPS entry.

Bests,
Guofeng

**Comment by EralpDemir** [comment]
Dear Goufeng,
Based on your feedback I have made the changes in the initialization file. I have also changed the structure of the PROPS slightly. 

With that I close this issue.

Bests,
Eralp

**Comment by 123fgh123** [comment]
OK,  Thank you very much.

Recently, I have found another issue in one element test: when the hardeningparam(3) of material-02 was changed from 2.5 to 0.25, the result seemed to be unreasonable. In the final deformation stage, the PEEQ would not change but the Mises stress   changed dramatically.  Please see attached files for detail.

![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/64315155/48b9a711-076b-4c84-9baa-ec52b593324a)

[One-element-test-Abq6.14-Intel2013.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/12836838/One-element-test-Abq6.14-Intel2013.zip)
[One-element-test-Abq2020-Intel2021.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/12836839/One-element-test-Abq2020-Intel2021.zip)

Bests,
Guofeng

**Comment by EralpDemir** [comment]
Hello,
I have checked. I could not find the poblem. I used the same strain rates and strains as in your input file. 

![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/90987045/1fd6050a-0761-4881-ac7e-067eda56abf0)


Sending the input file with the fortran files.
[check.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/12840923/check.zip)

Bests,
Eralp

**Comment by 123fgh123** [comment]
The issue would happen when the step parameter was set to 0.01, see following figure.
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/64315155/0bdc5bfb-5da0-4095-9a11-379f3d8048c2)

**Comment by EralpDemir** [comment]
Hi again,
Convergence may not be achieved for constant time stepping. Time stepping is an integral part of the crystal plasticity solver. If convergence is not achieved, a cut-back signal is sent to Abaqus to reduce the time steps. 

If you still want to use constant time stepping, you may try increasing the number of inner loop iterations which is a parameter in userinputs.f. 

Hope this helps,
Eralp

**Comment by 123fgh123** [comment]
Ok, thank you very much.

Bests,
Guofeng
