### ISSUE TITLE
Output total GND

### ISSUE THREAD

**Issue by akihoo** [TarletonGroup/CrystalPlasticity#33]
Hi Erlap,

I'm trying to output the total GND with the power law slip model, Voce type hardening model, and the GND model. I set the 6th State-variable output (Total statistically-stored dislocation density) to 1, but it is strange that the SDV I got is all zero even when the GND is non-zero. I didn't use the SSD model because I only care about the GND, so the statev_ssdtot should be the total GND. Is that right? Is there something that I was missing? Or how can I export the total GND?

Bests,
Feiyu

**Comment by EralpDemir** [comment]
Hi Feiyu,

The GND density is stored in a different state variable than SSD. It would be best to look at statev_gnd instead. You may write a custom output that sums up all the GNDs (absolute) in the useroutputs.f section.

SSD values and their hardening contribution to strength is taken care of by the tauc by the Voce law. So they will be set to zero initially and do not evolve since hardening is accounted by the Voce law.

Hope this helps,
Eralp

**Comment by akihoo** [comment]
> Hi Feiyu,
> 
> The GND density is stored in a different state variable than SSD. It would be best to look at statev_gnd instead. You may write a custom output that sums up all the GNDs (absolute) in the useroutputs.f section.
> 
> SSD values and their hardening contribution to strength is taken care of by the tauc by the Voce law. So they will be set to zero initially and do not evolve since hardening is accounted by the Voce law.
> 
> Hope this helps, Eralp

Oh, I see in the subroutine `totalandforest`, there are two type of total GND density:
```
      rhotot = ssd +
     + abs(gnd(1:nslip)) + ! edges
     + matmul(transpose(slip2screw), abs(gnd(nslip+1:nslip+nscrew))) ! screws

      rhotot = ssd +
     + abs(gnd(1:nslip)) + ! edges
     + matmul(transpose(slip2screw), abs(gnd(nslip+1:nslip+nscrew))) ! screws
!
!
!   
!     Scalar sum
      sumrhotot = sqrt(sum(gnd*gnd)) + ssdtot
```
What's the difference between the two types of total density.

**Comment by EralpDemir** [comment]
Hi,
In the earlier version of the code, the dislocation density was considered as the sum over the slip systems so it was a scalar measure. It was simpler and isotropic, the same CRSS for all slip systems. We wanted to also keep this method as an alternative for consistency with earlier approaches.

In the current version, we account for anisotropy in strength so the slip resistance is computed per slip system.

The use of average state variables can be triggered by setting "useaveragestatevariables=1" in userinputs.f.


We also differentiated SSDs and GNDs. We assume SSDs consists of equal screws and edges and so we use a mapping "slip2screw" to map dislocations to the corresponding screw systems evenly.

Forest density is used to relate CRSS in your case, it will be dependent on GND density, SSDs will not be in effect. The effect of Voce hardening will also be added to the CRSS as tauc. Please have a look at "crss.f".

I hope that clarifies your question,
Eralp
