### ISSUE TITLE
Hardening Model 4 

### ISSUE THREAD

**Issue by kushwaha-ajay** [TarletonGroup/CrystalPlasticity#35]
Hi Eralp,
I hope this message finds you well. I'd like to express my gratitude for sharing the code; it has been incredibly helpful in my work. As I was going through the code and the equations related to hardeningmodel = 4, I came across a discrepancy between the equation presented in the code documentation and the one cited in the reference  (https://doi.org/10.1016/j.actamat.2010.06.021). The equation in the documentation and code is:
![Screenshot 2023-10-26 144018](https://github.com/TarletonGroup/CrystalPlasticity/assets/145034715/9956a6f4-71cd-4716-8d4e-e7159b05b05c)
The equation mentioned in the cited paper is:
![Screenshot 2023-10-26 144355](https://github.com/TarletonGroup/CrystalPlasticity/assets/145034715/bcd80577-b029-43df-922d-2d45e5e990da)

Specifically, it appears that "b" is missing in the code documentation's equation when compared to the cited paper. I wanted to confirm whether I might be overlooking something or if there's an error or modification involved in the code.

Furthermore, I found another paper (https://doi.org/10.1016/j.ijplas.2019.09.002) where the authors have used the same hardening model, but in this case, "f" is missing for the same equation. The rest of the model appears to be quite similar to the one cited in the documentation. 
![Screenshot 2023-10-26 145753](https://github.com/TarletonGroup/CrystalPlasticity/assets/145034715/38fd8a54-0a9c-41b3-b776-bcb9dc3c3ae5)

My goal is to obtain a stress-strain curve for IN718. I have applied a strain of 1% in the x-direction, and I'm using slipmodel = 3 and hardeningmodel = 4. I have created a new custom material 11 by copying material 2 and commenting out Hintmat1 calculations. I've taken the material parameters from the paper (https://doi.org/10.1016/j.ijplas.2019.09.002). I got this as a response for S11 vs. LE11:

![Screenshot 2023-10-26 165326](https://github.com/TarletonGroup/CrystalPlasticity/assets/145034715/986c6538-1258-4f95-96d6-1d53f81ee6f8)

However, the response I'm getting is a straight line. I'm uncertain whether plotting S11 vs. LE11 is an accurate representation of the stress-strain curve. Is it happening due to parameter values or something else?

Thank you for all your help. I hope to hear back from you soon!

Best,
Ajay

**Comment by EralpDemir** [comment]
Hi Ajay,
About the equations, you are definitely correctly. I propably thought 1/b in the KM hardening term but it does not exist of the softening term.  Please feel free to add it, and I will give a correction in the next version.

In the Acta paper, "f" was used a factor (https://doi.org/10.1016/j.actamat.2010.06.021). Some works may prefer to embed everything in k2 to reduce the number of parameters.

You are getting a linear response. Please check whether you have slip rates at the beginning. It may be linked with parameters for CRSS. Please make sure to check that number, you may write a one element case.  

Let me know how it works

Best wishes,
Eralp

**Comment by EralpDemir** [comment]
Hey Ajay,

Also I wanted to remind that it may be important to change the parameter to "maxnmaterial=11" in userinputs.f.

**Comment by kushwaha-ajay** [comment]
Thank you for your quick response.
I will make that change in the code. I will try to adjust the parameter values to get the correct response.
Just to be on the same page, one element case would be the 1 x 1 x 1 micrometer cube geometry. Is that correct?
Yes, I had already adjusted "maxnmaterial=11" in userinputs.f.

I'll let you know the progress.

I had one more question: what changes do I need to make in the code to study the response of the material under cyclic loading?

Thanks again for the help!

**Comment by EralpDemir** [comment]
Hi Ajay,

Element size can depend on your problem, can take any value. It is in micrometer units.

You just need to change the BCs for cyclic loading.

**Comment by EralpDemir** [comment]
Thank you Ajay for raising this issue. 

I have corrected another error related with calculation of substructure density (rhosub). The increment "drhosub" in the hardening model-4 should be added over the slip systems.

I have released a new version including these changes, UMAT_v2.6. 

Bests,
Eralp

**Comment by kushwaha-ajay** [comment]
Thank you. I also spotted the same error last night. I was about to let you know.
Thank you for the update.

**Comment by kushwaha-ajay** [comment]
Hey Eralp,
I had one more doubt. Is the total density being computed for the hardening model 4 in the code? If yes, then in what file can I locate that?
![Screenshot 2023-11-02 113545](https://github.com/TarletonGroup/CrystalPlasticity/assets/145034715/9d5ccfc9-76c9-40b3-bbab-9f5265a406dc)

**Comment by EralpDemir** [comment]
It is stored in a state variable for substructure density. Total density is calculated in a subroutine called "totalandforest" at cpsolver.f but this is not used elsewhere or outputted.

**Comment by kushwaha-ajay** [comment]
Hey Eralp,
I had a question regarding backstress calculations using model 2. I am using UMATv2.6. Are the backstress values being used in the calculations of the final stress state? Also, I ran Model 2 (with gndmodel1) and stored the backstress values; all the values are zero. I am not sure why this is happening.

Thanks a lot for all the help.

Regards,
Ajay

**Comment by kushwaha-ajay** [comment]
Hey Eralp,
I wanted to follow up on the previous comment.

"I had a question regarding backstress calculations using model 2. I am using UMATv2.6. Are the backstress values being used in the calculations of the final stress state? Also, I ran Model 2 (with gndmodel1) and stored the backstress values; all the values are zero. I am not sure why this is happening. Any insight into this would be great."

Thank you again for your time and support.

**Comment by kushwaha-ajay** [comment]
Is backstressparam(1) for backstress model 2 or model 1?

Thank you for the quick response.

**Comment by EralpDemir** [comment]
It is for both. If it is not so in the version you are using, please ignore. GND-based backstress is under development, first results show that it does not work well.

**Comment by kushwaha-ajay** [comment]
Noted.
Thank you very much.

**Comment by kushwaha-ajay** [comment]
Hey Eralp,

I've been working with UMAT_v2.6 and encountered a few issues while using it with custom FCC material and Hardening Model 4. Here's what I observed:

1. Despite changing the hardening model parameters, the stress-strain curve remained identical across all variations. There was no change in the curve's response.
2. When I increased the number of grains in the RVE from 6 to 90, the stress-strain response became linear.
3. I conducted the same experiments using Hardening Model 3, and the response seemed fine. This made me wonder if there might be some errors specific to Hardening Model 4.
4. Additionally, I attempted cyclic loading again with hardening model 4, but I encountered a limitation—I couldn't run more than 2 cycles due to the error message "***ERROR: Too many attempts made for this increment." To resolve this, I changed the default maximum number of solution attempts from 5 to 30, but got the same error.

I've also tried using UMATv2.7, but unfortunately, these issues persist. Any insights or guidance on resolving these would be greatly appreciated.

Thanks!

**Comment by EralpDemir** [comment]
Hi Ajay,

The state variables; forest and subtructure density terms for hardening model-4 were not set properly. They need to have an initial value. 

I have made the changes for that model and ran it for a one element case. I am sending the version and .INP file. You may track the example hardening parameters from usermaterials.f for case(2).

I will publish this as v2.8 in the Github. 

The cyclic loading problems might be related to the model. Please try this and let me know. 

Hope this helps,
Eralp


[hmode4.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/13503515/hmode4.zip)

**Comment by kushwaha-ajay** [comment]
Thank you very much!
I will try this and let you know.

Regards,
Ajay

**Comment by kushwaha-ajay** [comment]
Hey Eralp,

I ran the code that you provided with modified HM4 for my case, and it works well now. I will let you know if I face any other problems regarding it.

Thank you very much for all your help.

Regards,
Ajay
