### ISSUE TITLE
2D EBSD data reconstruction by Dream3d,and generate Abaqus input files

### ISSUE THREAD

**Issue by mcren1** [TarletonGroup/CrystalPlasticity#36]
Hi eralp,
Thanks a lot for your helpful code. I am importing 2D Oxford EBSD Data (.ctf) into  Dream3d  , to realize the reconstruction and mesh of model, then generate Abaqus input files. Do you know how to set up dream3d to achieve this?  I would be extremely grateful for any insights, advice, or recommended resources you can offer. 

Best,
Mengchong Ren

**Comment by EralpDemir** [comment]
I think it would be better to ask the Dream3D group.

https://groups.google.com/g/dream3d-users?pli=1

If you raise this question, they address it regularly.

Bests,
Eralp

**Comment by mcren1** [comment]
Thank you very much for your advice!

Bests,
Mengchong Ren
