### ISSUE TITLE
Questions about creep

### ISSUE THREAD

**Issue by HappyLingJuan0323** [TarletonGroup/CrystalPlasticity#39]
Hello, excuse me to bother you:
You know that creep is not only related to temperature and stress, but also time is an indispensable factor. In the static analysis of ABAQUS, time is a variable with no practical significance, and no variables related to time are found in creep.f. So how do I use the UMAT subroutine to obtain a result that often appears in the literature!

![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/106541634/726b1e49-a3d2-4e7e-9647-0d5d9fbceafa)

**Comment by EralpDemir** [comment]
Yes, the creep model we have has temperature dependence. It should be able to capture these effects. 

Bests,
Eralp
