### ISSUE TITLE
can new version consider cohesive and twin?

### ISSUE THREAD

**Issue by mikejwg** [TarletonGroup/CrystalPlasticity#4]
Dear authors,

Thanks very much for your sharing. I remember the old code can consider the cohesive element and the effect of twin, but the new code deleted these functions.  Is it ok for these functions in the old code?  
Best regards,
Mike

**Comment by EralpDemir** [comment]
Hi,
Right now we do not have the effect of twinning and cohesive elements. We plan to add the cohesive elements but we do not consider modeling twinning, so please refer to the former version if you intend use them soon. The former version is under the folder "\old".
Thanks
