### ISSUE TITLE
Reference about the backstress model

### ISSUE THREAD

**Issue by akihoo** [TarletonGroup/CrystalPlasticity#41]
Hi Erlap,

Could you give me some reference to the backstress model in your code? including both the local and nonlocal backstress models. 

Thank you for your help,

Best regards,
Feiyu

**Comment by EralpDemir** [comment]
Hi Feiyu,

Unfortunately we have not published it yet. It is an on-going investigation. I will keep you posted with progress.

Thanks,
Eralp
