### ISSUE TITLE
Questions about using your code in the article

### ISSUE THREAD

**Issue by MengchongRen** [TarletonGroup/CrystalPlasticity#43]
Dear Eralp,

I hope this message finds you well. I am reaching out to you regarding the use of your codes in my study.

Your program is immensely valuable and essential for my research. As a matter of academic integrity and to ensure proper acknowledgment of your work, I wanted to inquire if you have any specific citation requirements or if there are any particular articles of yours you would prefer me to reference in my paper regarding the use of your  program. If there are any specific terms of use or licenses associated with the program, i would be glad to comply with them accordingly. Your guidance or any specific requirements you might have regarding citation in my paper would be immensely helpful for me.

Once again, thank you for your generosity in providing this resource to the academic community. Your assistance has been immensely appreciated and has significantly enriched our study.
I eagerly await your response. If you require any further information or have any queries, please feel free to reach out.

Best regards,
Ren Mengchong

**Comment by EralpDemir** [comment]
Hi Ren Mengchong,

The articles will be currently in preparation. I put some earlier related references to the readme directory of the code. Feel free to cite them. I will keep you posted for the related articles when released.

Best wishes,
Eralp

**Comment by MengchongRen** [comment]
Dear Eralp,

I hope this message finds you well. Thank you for your  response regarding the usage of your program code and related articles. Your provision of the earlier related references in the readme directory of the code will be immensely helpful for our work. We will certainly cite them accordingly in our publication. Once again, thank you for your response.

Best regards,
Ren Mengchong
