### ISSUE TITLE
Coupled thermal-stress analysis using UMATv2.9

### ISSUE THREAD

**Issue by kushwaha-ajay** [TarletonGroup/CrystalPlasticity#45]
Hello Eralp,

I hope you are doing well. I was trying the coupled temp-displacement step module using UMAT_v2.9 for one element case. However, this module uses the C3D8T element type, and the current UMAT version doesn't support this element type. I was interested in simulating behavior under variable temperature and variable strain loading conditions. Is there any way to perform this type of analysis using the current UMAT?
Also, I would appreciate it if you could provide references for CMSX-4 temperature-dependent properties used in the user material file.

Any leads would be very helpful. Thanks!

**Comment by EralpDemir** [comment]
Hi Ajay,

You may simply change in meshpropf. the case  "case('C3D8','C3D20R')" to "case('C3D8','C3D20R','C3D8T')" in feprop subroutine.


The reference for CSMX-4 is this one:
https://doi.org/10.1016/j.ijplas.2023.103589

Best,
Eralp

**Comment by kushwaha-ajay** [comment]
Thank you very much!

**Comment by kushwaha-ajay** [comment]
Hey Eralp,

Thanks again for all your help! In the UMAT file, it is mentioned in line 16 that multiple materials with different phases can co-exist in a mesh. How can we do that in a polycrystal RVE, as Matlab code takes only 1 MatID while generating the input file? Do we assign different materials in Abaqus by manually changing the material ID (row 5) of different grains? Or is there any other way to do this?

Thanks!
Ajay

**Comment by kushwaha-ajay** [comment]
Hey Eralp,

I was trying to fit the experimental hysteresis curve for cyclic loading with the simulation using UMATv2.9. I got the following plot (left is the experimental curve, and right is the simulation curve). I used slipmodel = 3, iphase = 2, hardening model = 1, backstress model = 1, and gndmodel =1 with 100 grains RVE with custom material. I was able to fit the experimental tensile curve, but I am not able to match it with the hysteresis curve. Can you please let me know what I could be missing to get better results? The shape in general is not close to the experimental curve.
![comp](https://github.com/TarletonGroup/CrystalPlasticity/assets/145034715/c077528e-d521-41d2-9a92-52706ea1002d)

Also, a separate question: I just wanted to confirm that the effect of twins is not incorporated in the current codes. Is that correct?

Regards,
Ajay

**Comment by EralpDemir** [comment]
Hi Ajay,
We have made an important update on the mapping of screw dislocations. That changes the hardening response. So I recommend to use the latest version with the latest updates.

You may calibrate cyclic response using two parameters, h and hD in A-F type model. I think with that you may improve those results. 

We do not have twinning incorporated but I was in the code which is still available \old folder using both continuum approach and with a phase field approach. We do not plan to include to this code because it extremely complicates the code structure.

Best,
Eralp

**Comment by kushwaha-ajay** [comment]
Hey Eralp,

1) What is the unit of the reaction force output?
2) Also, I had a question regarding plotting the stress-strain plot. How do you usually plot the stress-strain response of the whole cube (RVE) to validate it with the experimental engineering stress-strain curve? I know it's a very basic question, but I wanted to make sure that I followed the correct procedure to extract and plot the bulk response of the RVE.

For boundary conditions, I have followed your YouTube video tutorial.
Thanks for your continuous support.

Regards,
Ajay

**Comment by EralpDemir** [comment]
Hi Ajay,

1. The stress unit is MPa, dimensions are in micrometers, that makes force unit as microNewtons.
2. That is a good question. I think as if doing a tension experiment and we are measuring cross head displacement and forces from a transducer. The reaction forces are equivalent to measuring actual forces. So, simply dividing the sum of the reaction force by the undeformed area will give the engineering stress. Engineering strain can be obtained from dividing the displacement by the initial gauge length. There a conversion equation to convert engineering strains/stresses to true strains/stresses. 

Alternatively the stress average over the whole RVE of the stresses at the element centroids (which is the average of integration points) can be used but this becomes a little bit tedious if you have many elements.

Hope this helps.

Best,
Eralp

**Comment by kushwaha-ajay** [comment]
Thank you very much for the prompt response. I appreciate it.
