### ISSUE TITLE
Computation of Forest and Total Dislocations from GNDs 

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#46]
Subject: Inquiry about GND Implementation in CPSolver.f

Dear Eralp,

I trust this message finds you well. It's been a while since we last corresponded, back in the months of May-August, discussing various aspects of CPFEM and its implementation. Unfortunately, due to other professional commitments, I had to take a hiatus from working on this topic. However, I have recently resumed my efforts in this area.

During my review of the implementation of GNDs and the subroutine totalandforest in the file cpsolver.f, I noticed a discrepancy in the handling of normal components of edge dislocations compared to the conventional approach outlined in many references. Specifically, your implementation appears to omit the definition of the normal components of edge dislocations.

In the typical approach, the forest component of the GND involves considering contributions from both edge dislocations (in transverse and normal directions) and screw dislocations.

![Screenshot 2024-02-18 165303](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/8f5747cd-d79c-462d-b23d-9c642f9dfbd1)

However, in your code snippet, the normal components of edge dislocations are seemingly not defined.

![code](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/4335186e-5a75-4438-8b4f-a4e72531b301)
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/db13fd50-814c-4286-88ab-4a6d8eedbb59)

I am reaching out to seek clarification on the rationale behind this implementation choice. Any insights you can provide will be immensely helpful in understanding the nuances of your approach.

Thank you for your time and assistance.

Best regards,
Vikram

**Comment by EralpDemir** [comment]
Many thanks Vikram for your comments. 

That is right, we intentionally ignored the edge dislocations having their line direction along the slip plane normal. Physically it will be a jog which is harder to create with slip activation, may require multiple slip and a higher energy.

Model-1 and 2 does not use this geometrical limitation.

While this is true for models 3 and 4. 

You may include them to your analysis when using model 3 or 4 or you may simply use model 1 or 2.

Best,
Eralp

**Comment by vikramroybarc** [comment]
Subject: Further Inquiry Regarding Forest Dislocation Computation in CPSolver.f

Dear Eralp,

I appreciate your prompt response to my previous inquiry. I have another question that I hope you can help clarify.

In the screenshots from a reference (Crystal Plasticity Book by Dierk Raabe et al) provided above, it is evident that the computation of forest dislocations from both SSD and GND involves considering the interaction strength (X_ab) between different slip systems. However, upon reviewing the code implementation, I observed that no such factor is incorporated.

Could you please shed light on why there is a disparity in this aspect of the implementation? Understanding the rationale behind this choice will significantly contribute to my comprehension of the intricacies of your approach.

I have attached additional screenshots that support this observation for your reference.

Thank you once again for your time and assistance. Your insights are invaluable to me.

Best regards,
Vikram

Attachment: Additional Screenshots
![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/baf78769-d860-4198-8fb6-d267ac64913e)

![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/d9db4539-f21f-4f18-8170-937f48d50fb7)
