### ISSUE TITLE
Incorporating FIPs in the codes

### ISSUE THREAD

**Issue by kushwaha-ajay** [TarletonGroup/CrystalPlasticity#48]
Hey Eralp,

I wanted to output the FIPs (image attached - ref: https://onlinelibrary.wiley.com/doi/full/10.1111/ffe.13685). 

![image](https://github.com/TarletonGroup/CrystalPlasticity/assets/145034715/178c638b-252b-456c-9d6c-56ef306791f9)

I am not sure where to make the changes in the codes to get these as output. Can you please help me out?
I know it is too much to ask but if you have time, can you incorporate these changes? I am not familiar with Fortran, and it might take me a lot of time to figure it out. If it is not possible, can you please let me know where to make the changes to get these FIPs as output.

Thanks for your continuous support.

Regards,
Ajay

**Comment by EralpDemir** [comment]
Hi Ajay,

I would like to help but I should dedicate sometime for this. 

If you like we can have an online discussion. I will sometime next week,  you may contact me from my email:
eralp.demir@eng.ox.ac.uk

Best,
Eralp
