### ISSUE TITLE
A question about getting the statev_gmatinv

### ISSUE THREAD

**Issue by Zengcq99** [TarletonGroup/CrystalPlasticity#52]
Dear Enralp:
I raised a question yesterday about getting the 9 components of gmatinv matrix below your video on the Youtube. Thank you very much for your response. I checked the number of DEPVAR and tried again. I found that I could get the SDVs I wanted successfully if I used usermaterials.f, but if I set PROPS manually, the issue happened again that only total slip per slip system was recorded in the odb file. I wonder whether there are any other parameters in these files I need to modify to get other SDVs I want if I define the material properties using PROPS instead of using "usermaterials.f".

I have attached the files I simulated to pinpoint my issues.   

Thank you in advance and I am looking forward to your reply.

Best wishes

Zeng Chenq
[test.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/14916758/test.zip)

**Comment by EralpDemir** [comment]
Dear Zeng,

You forgot to add "1" to row 99 in your PROPS vector.

You may use the usermaterials.f for your material definitions to avoid similar issues.

I send an example case in the attached.

Best,
Eralp
[test.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/14932481/test.zip)

**Comment by Zengcq99** [comment]
Dear Eralp,

I am truly grateful for your patience and guidance. This issue was entirely due to my carelessness. Once again, thank you so much.

Yours sincerely
Zeng Chenqi
