### ISSUE TITLE
Inquiry about outputing the total deformation gradient on each node

### ISSUE THREAD

**Issue by NINGYURICHARD** [TarletonGroup/CrystalPlasticity#53]
Dear Eralp:

May I ask how to output the total deformation gradient on each node? I can only find the plastic and thermal part of the deformation gradient in 'globalvariables.f' file. Looking forward to your reply. Thank you very much!

Regards,
Richard

**Comment by EralpDemir** [comment]
Hi Richard,
You are right, there is not an available variable for the deformation gradient.

It is readily available in UMAT as DFGRD and DFRGD0 at the current and former time increments. We have left empty places in userouputs to allow users to define their owm outputs. It would be in this case similar as the definition of thermal or plastic deformation gradients. You may need to do some modifications in globalvariables.f, initializations.f, and useroutoutputs.f files.

Best,
Eralp

**Comment by NINGYURICHARD** [comment]
Dear Eralp:

May I ask a question about remeshing? Suppose that I get a result of CPFEM after some iterations using your UMAT, then I perform remeshing because of the bad quality of mesh.  So the next step is to interpolate all variables onto the new mesh to construct the stiffness matrix of FEM, and then we can continue the simulation. May I ask which variables I need to store and interpolate to the new mesh? Whether your UMAT can achieve this? Thank you very much!

Regards,
Richard
