### ISSUE TITLE
issue regarding to hardening model 4

### ISSUE THREAD

**Issue by Shuai0712** [TarletonGroup/CrystalPlasticity#54]
Dear Dr. Demir, thank you for sharing the CPFEM packages online and that is a great contribution to the community. When I was trying to use the latest version for hardening model 4 (the other hardening model works well), the segmentation error persists although I tried different methods such as reduce the time step, set initial value for dislocation densities including rho_0, rhofor_0, rhosub_0, change the material properties, input the number of the elements explicitly etc (please see attached for the inp and codes).
Could you please have a look at it when your are available? Thank you so much for your help and your contribution to the whole community.
[TEST.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/15100023/TEST.zip)

**Comment by EralpDemir** [comment]
Dear Shuai,
Thanks for your response.

I checked the code and fixed a bug.

Apart from that, some of the material parameters were missing in your usermaterials.f file. 

It is working now, I am sending the code in the attachments and I will put a new version to Github. 
[ToShuai.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/15112150/ToShuai.zip)

Please check and let me know.

Best,
Eralp

**Comment by Shuai0712** [comment]
Dear Dr Demir, thank you so much for your prompt reply, the code is working well now. 

I'd like to report another issue if this is fine. Specifically, I tried to run some 2D jobs using inp file generated by the 'Neper2Abaqus' Matlab code. The jobs run smoothly when the mesh is hex but the error below pops up when I switch the mesh type to tet (cpe6, cps6). 

'The area of 1868 elements (all elements in the model) is zero, small, or negative. Check coordinates or node numbering, or modify the mesh seed' 

I generated models in Abaqus using the element type cpe6, cps6 and it works well. Seems like the error stems from the Matlab code, maybe node numbering? considering that the first three nodes have to be defined counter-clockwise where you look at this face from inside the tetrahedral element.

Please see attached for the inp file and thank you for your help again.

Best Regards,
Shuai
[Job-1.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/15120484/Job-1.zip)

**Comment by EralpDemir** [comment]
Hi Shuai,

The Neper2Abaqus converter is prepared for 3D elements. These codes are not checked for a 2D case, might function wrong.

Please feel free to do modifications needed for your application in the matlab or the python code.

Best,
Eralp

**Comment by Shuai0712** [comment]
Thank you, Dr Demir.
