### ISSUE TITLE
HCP Slip Direction and Slip Plane Conversion for Schmid Factor Calculation

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#55]
Dear Eralp,

I'm writing to you regarding the code in file_initialization.f, specifically lines 1388-1405. This section seems to be converting slip planes and directions for HCP materials.
```
!         slip direction conversion
!         [uvtw]->[3u/2 (u+2v)*sqrt(3)/2 w*(c/a)])
          do is=1,30
              dir(is,1) = 3.*dir3h(is,1)/2.
              dir(is,2) = (dir3h(is,1) + 2.*dir3h(is,2))*sqrt(3.)/2.
              dir(is,3) = dir3h(is,4)*caratio
          end do
!
!
!         slip plane conversion
!         (hkil)->(h (h+2k)/sqrt(3) l/(c/a))
          do is=1,30
              nor(is,1) = nor3h(is,1)
              nor(is,2) = (nor3h(is,1) + 2.*nor3h(is,2))/sqrt(3.)
              nor(is,3) = nor3h(is,4)/caratio
          end do
!
```
While I understand the general concept, I'm unsure about the specific logic implemented here. these formulations are slightly different than those followed in MOOSE framework 
Ref: https://mooseframework.inl.gov/bison/source/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.html

![Screenshot_20240509_080319_Chrome](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/855d5898-d886-4bd0-86ed-820e91091a32)

Would you be able to point me towards any references that explain the conversion method used in the code snippet? and How these two formulations are different 

 Understanding the rationale behind these lines would be very helpful.

Thanks,

Regards
Vikram Roy

**Comment by vikramroybarc** [comment]
The slip plane transformation 
```
!         slip plane conversion
!         (hkil)->(h (h+2k)/sqrt(3) l/(c/a))
          do is=1,30
              nor(is,1) = nor3h(is,1)
              nor(is,2) = (nor3h(is,1) + 2.*nor3h(is,2))/sqrt(3.)
              nor(is,3) = nor3h(is,4)/caratio
          end do
!
```
is in line with that mentioned in MOOSE Framework document
All the values are multiplied with a

But I think that the slip direction transformation should be like this i.e. a factor of (3/2) should be multiplied to the third term
```
!         slip direction conversion
!         [uvtw]->[3u/2     (u+2v)*sqrt(3)/2     (3/2)*w*(c/a)])
!
````

**Comment by EralpDemir** [comment]
Thanks Vikram, you are asking good questions.

I actually took it from Dr. Roters. 

Please see version DAMASK 3.0 their lattice.f90 file - line 1954. 

The direction conventions is the same as in MOOSE but the values are multiplied by 3/2. The slip direction is multiplied with c/a ratio and plane normal is divided by c/a ratio in our case. While in MOOSE, it seems it is both divided which is strange.

Hope this helps
