### ISSUE TITLE
Question about slipmodel=2

### ISSUE THREAD

**Issue by louis96108** [TarletonGroup/CrystalPlasticity#57]
I've tried to use slipmodel2 in two ways, but I'm having problems with both. The model I used is from‘Example-Polycrystal with PROPS’
(1) I modified the slip model in case2 and changed it to slipmodel=2 with the corresponding parameter slipparam(1) = 2.54d6
slipparam(2) = 0.85，slipparam(3) = 1.36，slipparam(4) = 1.6d-19
(2) I changed the Material ID into 7, and try to use this material that inherently contains slipmodel2
However, in both cases there were problems and I didn't know how to fix them.
![wrong](https://github.com/TarletonGroup/CrystalPlasticity/assets/69557894/0cbd77e9-5b4c-4292-b594-9b928a608263)

**Comment by EralpDemir** [comment]
Hi,
I have tested these example cases with the latest version. They work, I added the updated files.

When using PROPS, these material properties shall be updated for all of the grains in the mesh, which is somewhat tedious.

I am sending a single crystal case with an element that uses materialID-7 for the given properties. I am also sending the usermaterial.f file that contains these values. I ran it and it worked for those material properties.

I have added an if statement to the slip law for slip that is negligibly small. Please use the latest version (v.20) in the Github or in the attached.

Let me know if you have any other issues. I close this issue this with this.

Best,
Eralp

[v2.20.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/15375147/v2.20.zip)
