### ISSUE TITLE
Question about negative GND density

### ISSUE THREAD

**Issue by louis96108** [TarletonGroup/CrystalPlasticity#59]
Dear Eralp,
First of all, thanks for updating the codes about hardeningmodel=2, it works now. As mentioned in your paper, positive and negative values appear in SDV of TotalGND. But I'm confused about the negative sign.
(1) A. ARSENLIS and D. M. PARKS specified that positive shear gradients corresponded to 'negative edge dislocations' and 'positive screw dislocations', and this was adopted in the code. If only the edge dislocation is considered, it seems that the positive or negative shear gradient can be determined from the positive or negative dislocation density in the result. However, if both edge and screw dislocations are considered, this judgment becomes confused. So what are the benefits of this regulation?
(2) Could you give some advice on the output of all positive GND? Can I modify this part of Straingradient.f to achieve all positive GND?
![图片](https://github.com/TarletonGroup/CrystalPlasticity/assets/69557894/6029f7e4-1b80-496d-9e0e-d1d304974ad4)
Looking forward to your reply.

Best Regards,
Aaron

**Comment by EralpDemir** [comment]
Hi Aaron,

Let me try to answer your questions:

A1. Yes, the signs are considered they are determined based on the gradient. The sign information is preserved and all possible edge and screw dislocations must be considered in the analysis. 

The increment of GND density has to be checked against a tolerance value. You may find more details in https://doi.org/10.1016/j.ijplas.2024.104013 

A2. You may take the absolute value of the outputs in the post processing. There is also another useroutput that gives the overall absolute value for the GND density, you may use that too. I would not recommend making changes in straingradients.f this will effect the calculations and the results.

Best,
Eralp
