### ISSUE TITLE
 Issues in the CP_Solver.for File

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#6]
Hi Eralp,

I have identified some issues in the CP_Solver.for file that I would like to bring to your attention. Could you please respond to the following queries?

1. In the CP_Solver.for file, lines 801-803 update the elastic strains in the crystal reference system as follows:
! Elastic strains in the crystal reference
dummy33_ = matmul(gmatinv,dummy33)
dummy33 = matmul(dummy33_,transpose(gmatinv))

! Vectorize
call matvec6(dummy33,dummy6)

! Shear corrections
dummy6(4:6) = 2.0*dummy6(4:6)

Eec = Eec_t + dummy6

However, in the rest of the subroutines (CP_Explicit, CP_Implicit, and CP_ForwardGradientPlastic), the update is performed differently:
! Elastic strains in the crystal reference
dummy33_ = matmul(transpose(gmatinv),dstrane33)
dummy33 = matmul(dummy33_,gmatinv)

! Vectorize
call matvec6(dummy33,dummy6)

! Shear corrections
dummy6(4:6) = 2.0*dummy6(4:6)

Eec = Eec_t + dummy6

I believe the second version is correct. Could you please clarify this?

2. The crystal orientations are updated using two different approaches in different subroutines. 
Approach 1 (lines 813-823 and in the CP_ForwardGradientPlastic subroutine) updates the orientations as follows
! Update orientations
! All orientation changes are elastic rotations
dW33=0.
dW33(1,2) = domega(1)
dW33(1,3) = -domega(2)
dW33(2,1) = -domega(1)
dW33(2,3) = domega(3)
dW33(3,1) = domega(2)
dW33(3,2) = -domega(3)

gmatinv = gmatinv_t + matmul(dW33,gmatinv_t)

Approach 2 (in the CP_Explicit and CP_Implicit subroutines) updates the orientations as follows:
! Orientation update
!
! Intermediate variable
dR = I3 - We*dt

! Invert or transpose since rotations are orthogonal
dR = transpose(dR)

! Update the crystal orientations
gmatinv = matmul(dR, gmatinv_t)

Can we follow a uniform approach for updating the crystal orientations in all parts of the code, as suggested below?
gmatinv = matmul(R_e, gmatinv_t)
Here, R_e is the elastic rotation tensor calculated as follows:
F_e = V_e * R_e
Or R_e = inv(V_e) * F_e

V_e is the elastic strench tensor calculated as V_e = sqrt( F_e*transpose(F_e))

And F_e is the elastic deformation gradient calculated as:
F = F_e * F_p
Or F_e = inv(F_p) * F

Since F_p and F are available in all subroutines, can we adopt this uniform approach for updating the crystal orientations throughout the CP_Solver.for file?

I hope to receive an early response.

Thank you.

Best regards,
Vikram Roy

**Comment by EralpDemir** [comment]
Thanks Vikram for your careful review of  the code.

About your comments my answers are as follows:

1. I missed the transpose in the cpsolver.f lines 801-803. Many thanks for that. I will correct this and update it as v.28. 

2. With this correction it is already a uniform approach. In FG method spins are computed therefore the elastic spin is used to update the orientation. However, in the others we do not calculate spins to avoid extra computation for outputs. Thanks for your suggestion, we already compute the elastic strains in the formulation so we do not prefer redo the inversion and strain calculations. I have checked FG outputs with CP_Implicit and CP_Explicit outputs and they give the same results. Your correction refers to the beginning of the deformation so probably that is why I missed it. 

Let us know if you would figure out any issues.

Thanks,
Eralp
