### ISSUE TITLE
monotonic hardening and cyclic softening behavior 

### ISSUE THREAD

**Issue by mikejwg** [TarletonGroup/CrystalPlasticity#60]
Dear Eralp,
I am deeply grateful for your generosity in sharing your code, which has served as an invaluable platform for our crystal plasticity research. We had previously delved into the matter of simulating cyclic loading using a backstress model, and I eagerly anticipate the publication of your work in this area.

Furthermore, I am curious to know if this code can be utilized to simulate the monotonic hardening and cyclic softening behavior of Inconel 718. If so, would there be a need to select a particular computational model? Your advice and suggestions in this matter would be of immense value to us.

Thank you for your time and assistance.

Best regards,
John

**Comment by EralpDemir** [comment]
Hi John,
Thanks for your interest.

Yes the model is capable to simulate monotonic and cyclic loading.

- For material selection, I would recommend custom user material for FCC (case-2). The slip law is power law which is the most conventional, and it has two parameters to be calibrated. The hardening law is Voce type which is also quite well known in literature, and it has in total 4 parameters to be calibrated including the latent hardening coefficient. Please have a look at the documentation attached.
[UMAT_Crystal_Plasticity.pdf](https://github.com/user-attachments/files/15903806/UMAT_Crystal_Plasticity.pdf)
.

- For the cyclic loading and modeling backstress effects, you may want to choose a Armstrong-Frederick backstress model. It is turned on by setting the parameter "backstressmodel=1" in userinputs.f. It has two parameters "A" and "AD" in Equation (5) of the reference (https://doi.org/10.1016/j.ijplas.2020.102887). These two parameters must be set in usermaterial.f using the variables backstressparam(1) and backstressparam(2) inside case(2). A=6500 MPa, and AD=245 MPa were used for steel and it can be used as a starting guess - https://doi.org/10.1016/j.ijsolstr.2021.111127. 

Hope this helps,
Eralp

**Comment by mikejwg** [comment]
Thank you for your suggestions. However, due to the absence of consideration for the softening effect caused by the accumulation of cyclic plastic strain, the model, though capable of simulating cyclic loading, has failed to exhibit cyclic softening despite testing several sets of back stress parameters, all resulting in cyclic hardening instead.

**Comment by EralpDemir** [comment]
You may try Kock-Mecking hardening model. It has a softening term in it.

**Comment by mikejwg** [comment]
In Equations 7.17 and 7.18 in UMAT_Crystal_Plasticity.pdf , we notice the appearance of the parameter k1 twice. In the accompanying table, k1 appears as two distinct hardening parameters, where hardeningparam(1) has a k1 value set to 200, while hardeningparam(2) has a k1 value set to 0. To investigate the phenomenon of cyclic softening, we have attempted to adjust the value of hardeningparam(2), increasing it gradually from 0 to 1000, but unfortunately, we have still not been able to observe the desired cyclic softening effect.

For Kock-Mecking hardening model,  the modified Kocks-Mecking model (https://doi.org/10.1016/j.ijplas.2021.102990  
,  https://linkinghub.elsevier.com/retrieve/pii/S0749641921000656); for a Voce type law,  the paper (https://doi.org/10.1016/j.ijfatigue.2018.04.018) proposed a method to simulate the cyclic softening.
