### ISSUE TITLE
Question about C3D8R

### ISSUE THREAD

**Issue by xiamucp** [TarletonGroup/CrystalPlasticity#61]
Dear Eralp,
I am deeply grateful for your sharing code, which provides lots of help for our crystal plasticity research. 

I have developed a finite element model with C3D8R element, and it works well with UMAT V2.7. But it failed with UMAT v2.20, which shows severe small DFGRD1 and not converge in the first increment. Would there be a need to give necessary change in meshprop? 

Thank you for your suggestions！

Best regards,
Chen

**Comment by EralpDemir** [comment]
Hi Chen,

I have tested the latest version on Github with a C3D8R element.

I entered a small value for the hourglass stiffness. It works. Sending the INP file in the attached.

GND model does not work for this type element.

[C3D8R.zip](https://github.com/user-attachments/files/16065095/C3D8R.zip)

Hope this helps,
Eralp
