### ISSUE TITLE
Issue of hardeningmodel3 in hardening.f

### ISSUE THREAD

**Issue by louis96108** [TarletonGroup/CrystalPlasticity#63]
Hi,
The evolution for SSD density should be like this:
![图片](https://github.com/TarletonGroup/CrystalPlasticity/assets/69557894/93a1e14a-e4a7-4ba9-bcdb-0738a24c5b2f)
and the annihilation constant has a relationship with k1:
![图片](https://github.com/TarletonGroup/CrystalPlasticity/assets/69557894/954179bb-93f7-4c92-a9cb-de4d3ed85b70)
However, in hardening.f line 304, 'dssd' is calculated by the following codes:
dssd(is) = (k1/b *dsqrt(rhofor(is))-k2*ssd(is))*absgammadot(is)*dt
k1 probably shouldn't be divided by b.

Best regards,
Louis

**Comment by EralpDemir** [comment]
Hi,
The original relation has 1/b in it. 

Indeed it does not matter if this embedded in k1 or not.  We just wanted to stick to the original relation.

have a look at: 
https://doi.org/10.1016/0001-6160(86)90148-3
Equation 7
