### ISSUE TITLE
Issue caused by units

### ISSUE THREAD

**Issue by louis96108** [TarletonGroup/CrystalPlasticity#64]
Hi,
In the globalvariables.f, the Boltzmann constant is set to 1.380649d-23 [m2 kg s-2 K-1].
And in hardening.f, line 298, the codes for calculating k2 are as follows:
k2 = k1*X*b/g*(1.-KBT/D/b**3*dlog(pdot/pdot0))
In the answers to other questions, the use of μm and MPa was mentioned. So, after putting the parameter from the Document into the code:
![图片](https://github.com/TarletonGroup/CrystalPlasticity/assets/69557894/d7dd2163-b36c-40a0-8d66-76833b57d7ac)
I feel that the part of the calculation that the Boltzmann constant is involved in is problematic due to the unit mismatch
![图片](https://github.com/TarletonGroup/CrystalPlasticity/assets/69557894/a755d9a4-fe10-4911-9771-2b35a73df3ca)
I look forward to hearing from you, thank you very much

Best regards！
Louis

**Comment by EralpDemir** [comment]
Hi,
The units of the entries should be consistent. 
Thanks

**Comment by cherry12306** [comment]
Hi, I have the same question. Should the final result look like this?
1.
<img width="390" alt="Image" src="https://github.com/user-attachments/assets/24d834c5-568c-4538-ad02-7ad3af372c9e" />
2.
<img width="390" alt="Image" src="https://github.com/user-attachments/assets/3d00fe44-4c91-441c-8c81-edb3c3665d36" />
3.
<img width="390" alt="Image" src="https://github.com/user-attachments/assets/4e3dfe5a-d11e-418a-b2e2-ba8d873d0c63" />
4.
<img width="390" alt="Image" src="https://github.com/user-attachments/assets/65bdb0ae-49ad-4d5e-8bc1-766d22d03b26" />
Is the unit of k₂ also 1/μm?
I look forward to your response. Thank you very much in advance.

**Comment by louis96108** [comment]
I think that according to the μm and MPa unit system, the item containing KB is missing 10^12. You can verify if it is correct.

**Comment by cherry12306** [comment]
I converted, and the result is that k2 should still have units. The unit is 1/um, right?
k₁ = 0.01​​ 1/um
​​X = 1.1
​​b = 2.48×10⁻⁴ μm 
​​g = 1.0×10⁻³​​
​​D = 90 MPa 
​​T = 298 K​​
​​KB = 1.380649×10 −11 μm³ · MPa / K ​​
pdot = 4.0×10⁻³ s⁻¹​​
​​pdot₀ = 10.0×10⁷ s⁻¹​  
k2 = k1*X*b/g*(1.-KBT/D/b**3*dlog(pdot/pdot0)).     

<img width="958" alt="Image" src="https://github.com/user-attachments/assets/100c3d42-87be-4534-a8dd-8c8bebd9d3a4" />

<img width="958" alt="Image" src="https://github.com/user-attachments/assets/6468b254-5013-42e7-9c90-44d5af0d509b" />

**Comment by louis96108** [comment]
k1 and b make the item before the parentheses no unit. As for the item in the parentheses, (μm^3*MPa/K*K)/(MPa*μm^3). k2 is unitless.

**Comment by louis96108** [comment]
Hi cherry12306，
Have you ever met the problem like Issue #92 ?

**Comment by cherry12306** [comment]
Hi Louis,
In the screenshot of the issue you encountered in  #92 , is the horizontal axis the strain LE11 and the vertical axis S11? I haven't encountered that problem before. The plot I got using Mises strain and Mises stress is as shown below.
However, the issue I'm facing is that the fitting never perfectly matches — the hardening seems to be too high. I've tried adjusting various hardening parameters.

<img width="310" alt="Image" src="https://github.com/user-attachments/assets/88a78614-4ef2-45c0-8b61-946b96a96963" />

**Comment by cherry12306** [comment]
The version that I used is v2.26.

**Comment by EralpDemir** [comment]
> I think that according to the μm and MPa unit system, the item containing KB is missing 10^12. You can verify if it is correct.

That is correct. But the unit correction is done at slip.f. So don't use a different value for KB. You may multiply KB with 10^12 inside the hardening.f. 

I will send a correction when I am back from annual leave.

Thanks

**Comment by louis96108** [comment]
Hi Prof. Eralp Demir and cherry12306,

Thank you very much for your reply, which gradually solved my confusion. Thank you, Prof. Eralp Demir, for taking the time to respond to our questions amidst your busy schedule. Wishing you a pleasant annual leave.

And cherry12306, may I ask when you get such curves, do you use ‘pdot’ in the calculation of k2 or a fixed value that is consistent with the macroscopic strain rate? The reason I'm asking this is because the curve in Issue #92 is what I get with ‘pdot’, and when I replace ‘pdot’ with 0.01 which is consistent with the macro-strain rate, I can get the normal stress-strain curve.

**Comment by cherry12306** [comment]
Hi, Louis,
Based on my current understanding of the program, the only parameter that can be input is `pdot0`, so I'm not quite sure how `pdot` is defined as a constant. I would really appreciate your guidance on this. 
I'm using the *power law + hardening 3* model. I also wanted to ask which version you are currently using, and whether you have encountered the issue I mentioned in #106.
Thank you.
Best regards.

**Comment by louis96108** [comment]
Hi cherry,
I also use version 2.26. I've seen this approach to defining pdot as a constant, probably in Acta Materialia, but I forgot the exact title, and I don't think it's very accurate. I used the same method just out of desperation to get a normal curve.
Thanks for your reply.
Best regards.

**Comment by cherry12306** [comment]
Hi, Louis
You're too kind. I don't think I was of much help. I suppose it's better to wait for Eralp's reply.
