### ISSUE TITLE
open() and read() do not match in readfiles subroutine of initializations.f

### ISSUE THREAD

**Issue by lixiaoyaol** [TarletonGroup/CrystalPlasticity#65]
Hello Erlap,

I want to ask a question about the unit of open() and read() are not the same. The code located in readfiles subroutine of initializations.f.

In line99: open(200,file=foldername // '/' // voxfilename,action='read',  status='old')
In line107: read(100,*) dummy(1:8)

Should the unit in read() is 200 to be consistent with the unite in open()? If the unit in read() choice of 100 a specific choice, could you be kindly tell me the reason.

Best regards,
Li Bofeng

**Comment by EralpDemir** [comment]
Hi Li,

That is correct. They must have the same number.

Thanks for your input, I will correct this in the new version.

Best,
Eralp
