### ISSUE TITLE
The `file` in open() function need to be a full path

### ISSUE THREAD

**Issue by lixiaoyaol** [TarletonGroup/CrystalPlasticity#67]
Hi, Eralp

The `file` parameter is defined as a relative path in open() function of write_statev_legend subroutine of useroutput.f., It is:
`open(100,file='../STATEV_legend.txt',action='write', status='replace')`

However,  when a file is opened in a user subroutine, ABAQUS assumes that it is  located in the scratch directory created for the simulation; therefore,  full path names must be used in the OPEN statements in the subroutine  to specify the location of the files.

Could you insert a comment upon that open() function or write it as a full path.

Best regards,
Li Bofeng

**Comment by lixiaoyaol** [comment]
Hi, Eralp

I would like to ask you another question. In the file that is: Documentation/UMAT_Crystal_Plasticity.pdf, the Eq.(2.7) and Eq.(2.8)  and Eq.(2.26) shows that:
$$\boldsymbol{L} = \frac{\boldsymbol{F} + \boldsymbol{F}^T }{2} \tag{2.7}$$
$$\boldsymbol{D} = \frac{\boldsymbol{F} + \boldsymbol{F}^T }{2} \tag{2.8}$$
$$\boldsymbol{L} = \frac{\dot{\boldsymbol{F}}  \boldsymbol{F}^{-1} }{2} \tag{2.26}$$

is that the Eq.(2.7) a mistake here?

**Comment by EralpDemir** [comment]
1. open file location comment: then you need to enter everytime the folder location, we wanted to avoid that.

2. Equation 2.7 was wrong, corrected. Thanks.
