### ISSUE TITLE
question about parameter setting

### ISSUE THREAD

**Issue by AliceNeper** [TarletonGroup/CrystalPlasticity#69]
Hello Enrlalp，I used your subroutine, but I did a lot of trial and error to fit the parameters, but I still couldn't get the desired stress-strain curve correctly, the GND3 model I used and the hardened model 3，would be highly appreciated if you could give me some suggestions on my parameters.
[nj27.zip](https://github.com/user-attachments/files/16369698/nj27.zip)
![4fbfb7dbc492e1564f65e10109499d26](https://github.com/user-attachments/assets/7a3481cf-de7b-4a1f-8955-f94878f90c2a)

**Comment by EralpDemir** [comment]
Hi,
You may start with a simple model, turn GND off.

Set the tauc0 (xtauc variable in usermaterials.f) such that it yields at 900MPa.

You have two different hardening regimes, I think you may try to capture an average response by changing the hardening model. You may use linear evolution law, hardening model=2 with only one constant. But you should use it with an initial SSD density equivalent to tauc0 and set tauc0=0.

Hope this helps,
Eralp

**Comment by AliceNeper** [comment]
Hello Enrlalp，I did as you said, and I wonder if the initial SSD dislocation density of 1350 per slip system is a reasonable number.

**Comment by EralpDemir** [comment]
Hi,
1350 1/micrometer^2 = 1.35 x 10^15 1/m^2 which is quite large for an initial density. I would keep it within 10^10-10^13 regime. You may increase the geometric factor from 0.25 to 0.5 to increase the effect of strength.
Best

**Comment by AliceNeper** [comment]
Hello Enrlalp，Thank you for your quick reply.
If I understand correctly, let tauc0 (yields at 900MPa) in the simple model be tauc0=SSD density?

**Comment by umatgaoshou** [comment]
My current issue is that the elastic region yields very quickly, and the yield strength does not increase unless I set the tauc0 or the initial dislocation density to a very high value (much higher than normal). As the author mentioned, the SSD density is within this range. However, I have seen some references that state that tauc0 has almost no effect for FCC materials and can be set to 0. Do you have any good methods to increase the yield strength over time?
![Uploading 1.png…]()

**Comment by umatgaoshou** [comment]
![Uploading 1.png…]()
