### ISSUE TITLE
NEED OF UMAT AND VUMAT CIODE STRUCTURE

### ISSUE THREAD

**Issue by Abhinab-iit-112** [TarletonGroup/CrystalPlasticity#72]
Dear Sir,
I am writing this message to let you know that I am currently Started learning about UMAT/VUMAT and i need a Proper tested Code Structure (with guidance details of what has been done in particular lines) for Micro-extrusion Process at high temp.
Also please guide me what are the steps for assigning the same in PROPERTY Module IN ABAQUS?
I badly need a code structure for learning and project purposes (**Micro-extrusion at high temp_ Material-Titanium grade 5**)
please help me in doing so.
@EralpDemir @TarletonGroup 
Best,
Abhinab
Waiting for a Positive Response

**Comment by EralpDemir** [comment]
Please see the documentation:
https://github.com/TarletonGroup/CrystalPlasticity/tree/master/Documentation

There are also youtube videos on how to use our code
