### ISSUE TITLE
I NEED A UMAT CODE or  (CODE STRCTURE) ffor MICRO-EXTRUSION AT HIGH TEMP.

### ISSUE THREAD

**Issue by Abhinab-iit-112** [TarletonGroup/CrystalPlasticity#73]
Dear sir,
Following your zip file naming DREAM3D2ABAQUS where all those UMAT SUBROUTINE files are there (screenshot attached below).
I have two doubts that i am requesting you to make me understand.
1. Please can you give an explanation for the code to understand your code structure (named as: -OXFORD-UMAT.f) where it contains all the other " .f " files. I am unable to understand your code.
2. Following your same pattern if i want to write an UMAT code for HIGH TEMPERATURE MICRO-EXTRUSION TEST where i want to create a Synthetic microstructure in DREAM3D and then doing simulation in ABAQUS to see at what TEMP. and Strain-rate Material flow is good. For that i need to develop an UMAT code.
So WHAT SHOULD BE THE FORMAT AND STRUCTURE OF WRITING SUCH A CODE AND WHAT ARE THE REQUIREMENTS FOR THIS CODE (BASICALLY WHAT DATA DO WE NEED TO WRITE THIS CODE?)
![WhatsApp Image 2024-09-01 at 11 13 16_3cf39fb3](https://github.com/user-attachments/assets/10c53949-70e7-48e1-b061-23b0ed6863ba)
Waiting for your +ve Response.
It will help me a lot if you guide me in this code.
Yours Sincerely,
Abhinab Rath
From INDIA, IIT MADRAS
Chennai
@EralpDemir @TarletonGroup

**Comment by EralpDemir** [comment]
Hi Aghinab,

1. Our manuscript about the code is under review for publication now. The documentation is available at:
https://github.com/TarletonGroup/CrystalPlasticity/blob/master/Documentation/UMAT_Crystal_Plasticity.pdf

3. I can help with using our code. I cannot help with writing your own UMAT code. For thermal problems UMAT works well if you solve for temperature with a standard abaqus model the resulting temperature for each element and ip returns to UMAT which you can enter temperature specific material model. In our UMAT we also account for the thermal expansions. If you need help with using our code, I can provide support. 

Please start with simples, follow the youtube videos for using the code and using Dream3D. The pipeline for Dream3D is also given in the folder:
https://github.com/TarletonGroup/CrystalPlasticity/tree/master/Dream3D2Abaqus


Best
