### ISSUE TITLE
Question about the 'Temperature'

### ISSUE THREAD

**Issue by louis96108** [TarletonGroup/CrystalPlasticity#77]
Hi Enrlalp,
There is a Temperature flag setting in the userinputs.f .
!     0: Temperature is defined by the field variable in ABAQUS in [K]
!     Material properties are entered once only at the initialization
!     1: Temperature is defined by the user (constant)
!     Material subroutine is entered every time step
For case '0', is it necessary to set a Taylor-Quinney coefficient(Inelastic heat fraction) ?

**Comment by EralpDemir** [comment]
Hi,
The part of plastic dissipation is converted to heat flux to compute the temperature distribution, but when case(0) is selected, it is a constant temperature assumption ignoring these heat sources.

If you like to include you may do it by adding a thermal solver and turn use a thermomechanical solution, but we left that to the user.

Best
