### ISSUE TITLE
Question：calculation of the hardening parameter matrixc

### ISSUE THREAD

**Issue by notleareM** [TarletonGroup/CrystalPlasticity#80]
Hi Erlap,

usermaterials.f  605--613 ：

          hintmat1 = hardeningparam(4)
          do k = 1, int(nslip/3.)     
	        do i = 1, 3
                  do j = 1, 3
                      hintmat1(3*(k-1)+i, 3*(k-1)+j)=1.
                  enddo
              enddo
          enddo

I would like to ask if the code here should be changed to the following form

          hintmat1 = hardeningparam(4)
          do k = 1, int(nslip/3.)     
	        do i = 1, 3
                  do j = 1, 3
                      if i==j hintmat1(3*(k-1)+i, 3*(k-1)+j)=1.
                  enddo
              enddo
          enddo

Thank you for your attention to this matter.

Best regards

**Comment by EralpDemir** [comment]
Nope, that is correct. 

Try this in matlab:
hintmat1=1.4*ones(12);
for k = 1: 4
for i = 1: 3
for j = 1: 3
hintmat1(3*(k-1)+i, 3*(k-1)+j)=1.;
end
end
end
