### ISSUE TITLE
Correction in Documentation

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#9]
Dear Eralp,

I have noticed a correction that needs to be made in the documentation. I have attached a screenshot below, highlighting the issue:
![Screenshot 2023-06-03 130558](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/f9d78ecb-87ad-4959-8b77-fa75c5e798f2)
Upon reviewing the equations marked in the screenshot, it appears that there might be an error. Specifically, it seems that the term "gamma_t" should be replaced with "gammadot _t".
I kindly request you to review this and if necessary correct it in future versions.

Best Regards,
Vikram Roy

**Comment by EralpDemir** [comment]
Many thanks Vikram, noted.

Eralp
